#!/bin/bash
python3 -m compileall "$PYFILE" # compile file with compileall module

# get pyc file containing compiled bytecodes and discard it's directory.
mv __pycache__/*.pyc "${PYFILE}c"
rm -r __pycache__
